### ISSUE TITLE
octomap_service话题问题

### ISSUE THREAD

**Issue by SrewPython** [hu-minghao/VINS-Fusion-Vehicle#1]
请问octomap_service需要订阅哪个话题呢，是相机的话题吗，可否把你的话题订阅信息给我借鉴一下呀，谢谢
还有就是需要重新标定相机和小车编码器的imu吗

**Comment by hu-minghao** [comment]
remap 到 /loop_fusion/octree或者相机的/depth/color/points 都可以。loop_fusion的点云有过滤，点云会更少但扫出来地图更平整一些。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月29日(周五) 上午9:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hu-minghao/VINS-Fusion-Vehicle] octomap_service话题问题 (Issue #1)




 
请问octomap_service需要订阅哪个话题呢，是相机的话题吗，可否把你的话题订阅信息给我借鉴一下呀，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hu-minghao** [comment]
相机和imu的标定视情况而定，不一定都要重标，可以做做看精度是否有明显提高。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月29日(周五) 上午9:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hu-minghao/VINS-Fusion-Vehicle] octomap_service话题问题 (Issue #1)




 
请问octomap_service需要订阅哪个话题呢，是相机的话题吗，可否把你的话题订阅信息给我借鉴一下呀，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SrewPython** [comment]
好的，我先试着能不能跑通，用的是zed2相机，先改下节点试试看，谢谢您的热心回复
